#!/usr/bin/env python3

import os 
import argparse
from colorama import Fore

os.system('clear')
print (Fore.LIGHTGREEN_EX,f'''
.▄▄ · ▪  • ▌ ▄ ·.  ▄▄▄·▄▄▌  ▄▄▄ .·▄▄▄▄• ▄▌·▄▄▄▄•·▄▄▄▄•
▐█ ▀. ██ ·██ ▐███▪▐█ ▄███•  ▀▄.▀·▐▄▄·█▪██▌▪▀·.█▌▪▀·.█▌
▄▀▀▀█▄▐█·▐█ ▌▐▌▐█· ██▀·██▪  ▐▀▀▪▄██▪ █▌▐█▌▄█▀▀▀•▄█▀▀▀•
▐█▄▪▐█▐█▌██ ██▌▐█▌▐█▪·•▐█▌▐▌▐█▄▄▌██▌.▐█▄█▌█▌▪▄█▀█▌▪▄█▀
 ▀▀▀▀ ▀▀▀▀▀  █▪▀▀▀.▀   .▀▀▀  ▀▀▀ ▀▀▀  ▀▀▀ ·▀▀▀ •·▀▀▀ • V 2.0
 MultiFuzz - beta                Code by varel security             
''')
parser = argparse.ArgumentParser()
parser.add_argument('-l','--list', required=True, help="Masukan list url eg : url.txt")
parser.add_argument('-w','--wordlist' ,help="Masukan letak wordlist anda")
args = parser.parse_args()

wordlist_url = open(args.list,'r')
list_url = wordlist_url.readlines()

for url in list_url:
    lists = url.strip()
    os.system(f'sfuzz -u {lists}/ -w {args.wordlist}')